np.sort

return a sorted copy of an array

In [4]:
import numpy as np

a = np.random.randint(1,100,15)
np.sort(a)

array([ 8, 14, 20, 23, 45, 52, 63, 66, 66, 76, 80, 82, 86, 86, 86])

In [6]:
b = np.random.randint(1,100,24).reshape(4,6)
np.sort(b)

array([[ 9, 17, 50, 87, 88, 92],
       [11, 55, 65, 68, 83, 94],
       [ 9, 20, 48, 53, 88, 90],
       [ 7, 18, 45, 61, 80, 86]])

In [8]:
# axis = 0 column and axis = 1 row

np.sort(b,axis=0)

array([[ 9, 17,  7, 20,  9, 53],
       [11, 18, 83, 50, 45, 80],
       [48, 55, 87, 65, 68, 88],
       [61, 90, 88, 86, 92, 94]])

In [9]:
np.sort(b,axis = 1)



array([[ 9, 17, 50, 87, 88, 92],
       [11, 55, 65, 68, 83, 94],
       [ 9, 20, 48, 53, 88, 90],
       [ 7, 18, 45, 61, 80, 86]])

In [10]:
np.sort(a)[::-1]

array([86, 86, 86, 82, 80, 76, 66, 66, 63, 52, 45, 23, 20, 14,  8])

np.append()

np.append() appends values along the mentioned axis at the end of the array

In [11]:
a

array([80, 45, 66, 23, 66, 86, 20, 86, 82, 14, 63, 52, 86,  8, 76])

In [14]:
np.append(a,100)

array([ 80,  45,  66,  23,  66,  86,  20,  86,  82,  14,  63,  52,  86,
         8,  76, 100])

In [15]:
np.sort(a)

array([ 8, 14, 20, 23, 45, 52, 63, 66, 66, 76, 80, 82, 86, 86, 86])

In [16]:
b

array([[ 9, 17, 87, 50, 92, 88],
       [11, 55, 83, 65, 68, 94],
       [48, 90, 88, 20,  9, 53],
       [61, 18,  7, 86, 45, 80]])

In [17]:
np.append(b,np.ones((b.shape[0],1)),axis = 1)

array([[ 9., 17., 87., 50., 92., 88.,  1.],
       [11., 55., 83., 65., 68., 94.,  1.],
       [48., 90., 88., 20.,  9., 53.,  1.],
       [61., 18.,  7., 86., 45., 80.,  1.]])

In [18]:
np.append(b,np.random.random((b.shape[0],1)),axis = 1)

array([[ 9.        , 17.        , 87.        , 50.        , 92.        ,
        88.        ,  0.17954088],
       [11.        , 55.        , 83.        , 65.        , 68.        ,
        94.        ,  0.91909866],
       [48.        , 90.        , 88.        , 20.        ,  9.        ,
        53.        ,  0.12495523],
       [61.        , 18.        ,  7.        , 86.        , 45.        ,
        80.        ,  0.58276205]])

##np.concatenate()

np.concatenate() function concatenate a sequence of arrays along with an existing axis

In [22]:
a = np.arange(6).reshape(2,3)
b = np.arange(6,12).reshape(2,3)
print(a)
print(b)

np.concatenate((a,b),axis = 0)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

##np.unique()

np.unique() we get the unique values from an given array

In [23]:
e = np.array([1,1,1,2,2,2,2,4,3,4,5,4,4,6])

np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [25]:
f = np.array([[1,2,3,2,2,1,4,],[3,3,4,5,4,5,6]])

np.unique(f)

array([1, 2, 3, 4, 5, 6])

##np.expand_dims

with the help of Numpy.expand_dims() method, we can get the expanded dimension of the array

In [27]:
e = np.random.randint(1,100,15)
e

array([31, 71, 26, 74, 45,  8, 19, 83, 71, 55, 82, 24, 58,  7, 62])

In [28]:
np.expand_dims(e,axis = 0)

array([[31, 71, 26, 74, 45,  8, 19, 83, 71, 55, 82, 24, 58,  7, 62]])

In [29]:
np.expand_dims(e,axis = 0).shape

(1, 15)

In [30]:
np.expand_dims(e,axis = 1)

array([[31],
       [71],
       [26],
       [74],
       [45],
       [ 8],
       [19],
       [83],
       [71],
       [55],
       [82],
       [24],
       [58],
       [ 7],
       [62]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [31]:
f = np.random.randint(1,100,15)
f

array([47, 31, 24, 65, 60,  4, 79, 33, 64, 59,  9, 34, 32, 45, 20])

In [33]:
#find all the indices with value greater than 50

np.where(f>50)

(array([3, 4, 6, 8, 9]),)

In [35]:
# replace all values greater than 50 with 0

np.where(f>50,0,f)

array([47, 31, 24,  0,  0,  4,  0, 33,  0,  0,  9, 34, 32, 45, 20])

In [36]:
# replace all even numbers with 0

np.where(f % 2 == 0,0,f)

array([47, 31,  0, 65,  0,  0, 79, 33,  0, 59,  9,  0,  0, 45,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [37]:
f

array([47, 31, 24, 65, 60,  4, 79, 33, 64, 59,  9, 34, 32, 45, 20])

In [38]:
np.argmax(f)

np.int64(6)

In [39]:
np.max(f)

np.int64(79)

In [43]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[98, 68, 28, 42],
       [76, 93, 75, 83],
       [33, 30, 59, 90],
       [39, 37, 91, 54],
       [78, 83, 48, 69],
       [37, 27, 82, 67]])

In [45]:
np.argmax(b,axis = 1)

array([0, 1, 3, 2, 1, 2])

In [46]:
np.argmin(b,axis = 0)

array([2, 5, 0, 0])

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [47]:
b

array([[98, 68, 28, 42],
       [76, 93, 75, 83],
       [33, 30, 59, 90],
       [39, 37, 91, 54],
       [78, 83, 48, 69],
       [37, 27, 82, 67]])

In [48]:
np.cumsum(b,axis = 0)

array([[ 98,  68,  28,  42],
       [174, 161, 103, 125],
       [207, 191, 162, 215],
       [246, 228, 253, 269],
       [324, 311, 301, 338],
       [361, 338, 383, 405]])

In [51]:
a = np.array([1,2,3,4])

In [52]:
np.cumsum(a)

array([ 1,  3,  6, 10])

In [53]:
np.cumprod(a)

array([ 1,  2,  6, 24])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [54]:
a = np.random.randint(1,100,15)
a

array([58, 78, 14, 90, 86, 14, 67, 52,  5, 62, 28, 75, 84, 70, 39])

In [56]:
np.percentile(a,100)

np.float64(90.0)

In [57]:
np.percentile(a,0)

np.float64(5.0)

In [58]:
np.percentile(a,50)

np.float64(62.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [59]:
a

array([58, 78, 14, 90, 86, 14, 67, 52,  5, 62, 28, 75, 84, 70, 39])

In [63]:
np.histogram(a,bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 1, 1, 0, 2, 2, 3, 2, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [64]:
np.histogram(a,bins = [0,50,100])

(array([ 5, 10]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [65]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [66]:
a

array([58, 78, 14, 90, 86, 14, 67, 52,  5, 62, 28, 75, 84, 70, 39])

In [68]:
items = [18,30,20,55,65,14,52,5,9,10]

np.isin(a,items)

array([False, False,  True, False, False,  True, False,  True,  True,
       False, False, False, False, False, False])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [69]:
a

array([58, 78, 14, 90, 86, 14, 67, 52,  5, 62, 28, 75, 84, 70, 39])

In [70]:
np.flip(a)

array([39, 70, 84, 75, 28, 62,  5, 52, 67, 14, 86, 90, 14, 78, 58])

In [72]:
b

array([[98, 68, 28, 42],
       [76, 93, 75, 83],
       [33, 30, 59, 90],
       [39, 37, 91, 54],
       [78, 83, 48, 69],
       [37, 27, 82, 67]])

In [74]:
np.flip(b,axis = 1)

array([[42, 28, 68, 98],
       [83, 75, 93, 76],
       [90, 59, 30, 33],
       [54, 91, 37, 39],
       [69, 48, 83, 78],
       [67, 82, 27, 37]])

In [75]:
np.flip(b)

array([[67, 82, 27, 37],
       [69, 48, 83, 78],
       [54, 91, 37, 39],
       [90, 59, 30, 33],
       [83, 75, 93, 76],
       [42, 28, 68, 98]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [76]:
a

array([58, 78, 14, 90, 86, 14, 67, 52,  5, 62, 28, 75, 84, 70, 39])

In [80]:
np.put(a,[0,1],[580,1400])

In [81]:
a

array([ 580, 1400,   14,   90,   86,   14,   67,   52,    5,   62,   28,
         75,   84,   70,   39])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [82]:
a

array([ 580, 1400,   14,   90,   86,   14,   67,   52,    5,   62,   28,
         75,   84,   70,   39])

In [84]:
np.delete(a,1)

array([580,  14,  90,  86,  14,  67,  52,   5,  62,  28,  75,  84,  70,
        39])

In [85]:
np.delete(a,[0,2,5])

array([1400,   90,   86,   67,   52,    5,   62,   28,   75,   84,   70,
         39])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [88]:
m = np.array([1,2,3,4,5])
n = np.array([5,6,7,8,9,10])

np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
np.intersect1d(m,n)

array([5])

In [90]:
np.in1d(m,n)

/tmp/ipython-input-207282267.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n)


array([False, False, False, False,  True])

In [91]:
np.setdiff1d(m,n)

array([1, 2, 3, 4])

In [92]:
np.setxor1d(m,n)

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [93]:
a

array([ 580, 1400,   14,   90,   86,   14,   67,   52,    5,   62,   28,
         75,   84,   70,   39])

In [94]:
np.clip(a,a_min = 25,a_max = 75)

array([75, 75, 25, 75, 75, 25, 67, 52, 25, 62, 28, 75, 75, 70, 39])