### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
# Creating numpy arrays

import numpy as np

In [ ]:
a = np.array([1,2,3])

print(a)

[1 2 3]


In [ ]:
b = np.array([[1,2],[3,4]])

In [ ]:
b

array([[1, 2],
       [3, 4]])

In [ ]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#dtype

np.arange(1,11,dtype=float)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#with reshape

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#np ones and np zeroes

# used for initialization

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.random

np.random.random((3,4))

array([[0.22686582, 0.34650067, 0.80812961, 0.66051093],
       [0.71952366, 0.23518571, 0.2408822 , 0.18211286],
       [0.19464379, 0.77258906, 0.76826354, 0.09320202]])

In [ ]:
#np.linspace   linear space

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
#np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
#ndim

a1.ndim

1

In [ ]:
a2.ndim

2

In [ ]:
#shape

a1.shape

(10,)

In [ ]:
a2.shape

(3, 4)

In [ ]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.size

8

In [ ]:
a2.size

12

In [ ]:
#itemsize -> will tell the size of each item

a1.itemsize

4

In [ ]:
#dtype

print(a1.dtype)

int32


In [ ]:
print(a2.dtype)

float64


In [ ]:
print(a3.dtype)

int64


#Changing Datatype

In [ ]:
#astype

In [ ]:
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a3.dtype

dtype('int64')

#Array Operations

In [3]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [4]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
#scalar opeartions

#arithmetic

a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [7]:
a1 + 2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [8]:
a1 / 2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [9]:
a1 - 2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [10]:
#relational

a2 > 15

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [12]:
#vector operations

a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

#Array Function

In [13]:
a1 = np.random.random((3,4))
a1 = np.round(a1 * 100)

a1

array([[42.,  9., 91., 62.],
       [92., 36., 77., 11.],
       [64., 86., 18., 81.]])

In [14]:
#min/max/sum/prod

np.min(a1)

np.float64(9.0)

In [15]:
np.max(a1)

np.float64(92.0)

In [16]:
np.sum(a1,axis = 0)

array([198., 131., 186., 154.])

In [17]:
# 0 -> col, 1 -> row

np.min(a1,axis = 0)

array([42.,  9., 18., 11.])

In [18]:
np.min(a1,axis = 1)

array([ 9., 11., 18.])

In [19]:
#trignometric function

np.sin(a1)

array([[-0.91652155,  0.41211849,  0.10598751, -0.7391807 ],
       [-0.77946607, -0.99177885,  0.99952016, -0.99999021],
       [ 0.92002604, -0.92345845, -0.75098725, -0.62988799]])

In [22]:
#mean/median/std/var

np.mean(a1)

np.float64(55.75)

In [23]:
np.median(a1)

np.float64(63.0)

In [21]:
# dot product

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a2)
np.dot(a2,a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [24]:
#log and exponents

np.log(a1)

array([[3.73766962, 2.19722458, 4.51085951, 4.12713439],
       [4.52178858, 3.58351894, 4.34380542, 2.39789527],
       [4.15888308, 4.4543473 , 2.89037176, 4.39444915]])

In [25]:
np.exp(a1)

array([[1.73927494e+18, 8.10308393e+03, 3.31740010e+39, 8.43835667e+26],
       [9.01762841e+39, 4.31123155e+15, 2.75851345e+33, 5.98741417e+04],
       [6.23514908e+27, 2.23524660e+37, 6.56599691e+07, 1.50609731e+35]])

In [29]:
#round/ceil/floor

np.round(np.random.random((2,3))*100)

array([[10., 93., 30.],
       [33., 72., 28.]])

In [30]:
np.floor(np.random.random((2,3))*100)

array([[55., 67., 46.],
       [28., 58., 42.]])

In [31]:
np.ceil(np.random.random((2,3))*100)

array([[ 3., 37., 84.],
       [ 2., 72., 75.]])

In [ ]:
# Indexing and slicing

In [35]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
a2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
a1[-1]

np.int64(9)

In [37]:
a2[0][3]

np.int64(3)

In [39]:
a3[0][1][0]

np.int64(2)

In [40]:
a1[0:4]

array([0, 1, 2, 3])

In [42]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a2[0,:]

array([0, 1, 2, 3])

In [49]:
a2[-1,:]

array([ 8,  9, 10, 11])

In [50]:
a2[:,2]

array([ 2,  6, 10])

In [51]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [52]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [56]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [57]:
a2[1,::3]

array([4, 7])

In [60]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [63]:
a3 = np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
a3[0,1]

array([3, 4, 5])

In [67]:
a3[1,:,1]

array([10, 13, 16])

In [68]:
a3[-1,1:,1:]

array([[22, 23],
       [25, 26]])

In [69]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

#Iterating

In [73]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [76]:
a2

for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [72]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [77]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [80]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


#Reshaping

In [ ]:
#reshape

In [81]:
#transpose

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
a2.transpose()
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [86]:
a2.ravel() # kitne bhi dimension ke array ko 1d m krdega

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [87]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [88]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

#Stacking

In [89]:
#horizontal stacking

a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [90]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [93]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [94]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [95]:
np.hstack((a4,a5,a4))

array([[ 0,  1,  2,  3, 12, 13, 14, 15,  0,  1,  2,  3],
       [ 4,  5,  6,  7, 16, 17, 18, 19,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 20, 21, 22, 23,  8,  9, 10, 11]])

#Splitting

In [97]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [100]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]